# Generated by Django 5.1.1 on 2024-09-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='client',
        ),
        migrations.DeleteModel(
            name='Prestation',
        ),
        migrations.RemoveField(
            model_name='service',
            name='client',
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
