# Generated by Django 5.1.1 on 2024-11-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client_infos',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
