# Generated by Django 5.1.1 on 2024-11-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_alter_client_infos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_creation'], name='factures_fa_date_cr_a279ff_idx'),
        ),
    ]
