# Generated by Django 5.1.1 on 2024-11-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_facture_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_infos',
            name='img',
            field=models.ImageField(blank=True, default='default-avatar.png', upload_to='clients/'),
        ),
    ]
