# Generated by Django 5.1.1 on 2024-11-26 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='factures.devis'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='factures.facture'),
        ),
    ]
