# Generated by Django 5.1.1 on 2024-09-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_prestationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestationtype',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
