# Generated by Django 5.1.1 on 2024-09-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0006_prestationtype_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poste_occuped',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
