# Generated by Django 5.1.1 on 2024-09-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0008_poste_facture_prestation_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='facture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='factures.facture'),
        ),
    ]
