# Generated by Django 5.1.1 on 2024-09-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0010_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
