import { FaProjectDiagram, FaRegFileAlt, FaLaptopCode, FaMobileAlt, FaClipboardList } from "react-icons/fa";
import { FaCode, FaServer, FaUserCog, FaNetworkWired, FaCloud } from "react-icons/fa";

export const projects = [
    {
        id: 1,
        name: "Développement Web",
        detail: "Demande de devis pour un projet de développement web.",
        icon: <FaLaptopCode />,
        entreprise: "Web Solutions",
        entreprise_address: "1 allée des développeurs",
        entreprise_phone: "0654324561",
        siret: "23478986543",
        city: "Lyon",
        price: "$750"
    },
    {
        id: 2,
        name: "Maintenance Site",
        detail: "Demande de maintenance pour site existant.",
        icon: <FaRegFileAlt />,
        entreprise: "Tech Innovators",
        entreprise_address: "42 rue de l'innovation",
        entreprise_phone: "0634567890",
        siret: "34567891234",
        city: "Marseille",
        price: "$750"
    },
    {
        id: 3,
        name: "Application Mobile",
        detail: "Demande de devis pour une application mobile.",
        icon: <FaMobileAlt />,
        entreprise: "App Creators",
        entreprise_address: "12 rue des applications",
        entreprise_phone: "0678901234",
        siret: "45678902345",
        city: "Paris",
        price: "$750"
    },
    {
        id: 4,
        name: "Stratégie Numérique",
        detail: "Consultation pour stratégie numérique.",
        icon: <FaClipboardList />,
        entreprise: "Digital Experts",
        entreprise_address: "23 avenue des stratégies",
        entreprise_phone: "0689123456",
        siret: "56789013456",
        city: "Lille",
        price: "$750"
    },
    {
        id: 5,
        name: "Recherche Prestataires",
        detail: "Recherche de prestataires pour un projet.",
        icon: <FaProjectDiagram />,
        entreprise: "Creative Agency",
        entreprise_address: "34 rue de la créativité",
        entreprise_phone: "0691234567",
        siret: "67890124567",
        price: "$750",
        city: "Bordeaux",
    },
    {
        id: 6,
        name: "Développement API",
        detail: "Création d'API pour intégration de services.",
        icon: <FaCode />,
        entreprise: "API Masters",
        entreprise_address: "7 rue des API",
        entreprise_phone: "0612345678",
        siret: "78901235678",
        price: "$750",
        city: "Nice"
    },
    {
        id: 7,
        name: "Hébergement Web",
        detail: "Solutions d'hébergement pour sites web.",
        icon: <FaServer />,
        entreprise: "Host Pro",
        entreprise_address: "99 rue des serveurs",
        entreprise_phone: "0609876543",
        siret: "89012346789",
        price: "$750",
        city: "Strasbourg"
    },
    {
        id: 8,
        name: "Consultation SEO",
        detail: "Optimisation pour moteurs de recherche.",
        icon: <FaUserCog />,
        entreprise: "SEO Gurus",
        entreprise_address: "14 avenue du référencement",
        entreprise_phone: "0654321567",
        siret: "90123457890",
        price: "$750",
        city: "Toulouse"
    },
    {
        id: 9,
        name: "Sécurité Informatique",
        detail: "Audit et conseils en sécurité informatique.",
        icon: <FaNetworkWired />,
        entreprise: "Cyber Safe",
        entreprise_address: "8 rue de la sécurité",
        entreprise_phone: "0698765432",
        siret: "01234568901",
        price: "$750",
        city: "Nantes"
    },
    {
        id: 10,
        name: "Cloud Computing",
        detail: "Solutions de cloud pour entreprises.",
        icon: <FaCloud />,
        entreprise: "Cloud Solutions",
        entreprise_address: "20 rue des nuages",
        entreprise_phone: "0678907654",
        siret: "12345679012",
        price: "$750",
        city: "Rennes"
    },
    {
        id: 11,
        name: "Développement e-Commerce",
        detail: "Création de solutions e-commerce sur mesure.",
        icon: <FaLaptopCode />,
        entreprise: "E-Shop Builders",
        entreprise_address: "5 rue des boutiques",
        entreprise_phone: "0656789012",
        siret: "23456789012",
        price: "$750",
        city: "Lille"
    },
    {
        id: 12,
        name: "Développement CRM",
        detail: "Solutions CRM pour gestion des clients.",
        icon: <FaRegFileAlt />,
        entreprise: "CRM Experts",
        entreprise_address: "13 rue des relations",
        entreprise_phone: "0612345679",
        siret: "34567890123",
        price: "$750",
        city: "Marseille"
    },
    {
        id: 13,
        name: "Développement de jeux",
        detail: "Création de jeux vidéo innovants.",
        icon: <FaMobileAlt />,
        entreprise: "Game Dev Studio",
        entreprise_address: "18 rue des jeux",
        entreprise_phone: "0659876543",
        siret: "45678901234",
        price: "$750",
        city: "Paris"
    },
    {
        id: 14,
        name: "Développement IoT",
        detail: "Solutions pour objets connectés.",
        icon: <FaProjectDiagram />,
        entreprise: "IoT Innovations",
        entreprise_address: "3 rue des objets connectés",
        entreprise_phone: "0634567891",
        siret: "56789012345",
        price: "$750",
        city: "Toulouse"
    },
    {
        id: 15,
        name: "Analyse de données",
        detail: "Services d'analyse et de visualisation de données.",
        icon: <FaClipboardList />,
        entreprise: "Data Insights",
        entreprise_address: "11 avenue des données",
        entreprise_phone: "0691234568",
        siret: "67890123456",
        price: "$750",
        city: "Bordeaux"
    },
    {
        id: 16,
        name: "Formation Informatique",
        detail: "Sessions de formation sur divers outils informatiques.",
        icon: <FaCode />,
        entreprise: "Tech Academy",
        entreprise_address: "15 rue des formations",
        entreprise_phone: "0678901235",
        siret: "78901234567",
        price: "$750",
        city: "Nice"
    },
    {
        id: 17,
        name: "Développement de site vitrine",
        detail: "Création de sites vitrines pour entreprises.",
        icon: <FaLaptopCode />,
        entreprise: "Web Showcase",
        entreprise_address: "25 rue des vitrines",
        entreprise_phone: "0634567894",
        siret: "89012345678",
        price: "$750",
        city: "Lyon"
    },
    {
        id: 18,
        name: "Intégration de systèmes",
        detail: "Intégration de systèmes et solutions informatiques.",
        icon: <FaUserCog />,
        entreprise: "System Integrators",
        entreprise_address: "28 avenue de l'intégration",
        entreprise_phone: "0612345671",
        siret: "90123456789",
        price: "$750",
        city: "Marseille"
    },
    {
        id: 19,
        name: "Développement d'applications SaaS",
        detail: "Création de solutions SaaS sur mesure.",
        icon: <FaCloud />,
        entreprise: "SaaS Innovators",
        entreprise_address: "9 rue des SaaS",
        entreprise_phone: "0678901239",
        siret: "12345678901",
        price: "$750",
        city: "Paris"
    },
    {
        id: 20,
        name: "Développement de plugins",
        detail: "Création de plugins pour diverses plateformes.",
        icon: <FaProjectDiagram />,
        entreprise: "Plugin Masters",
        entreprise_address: "30 rue des plugins",
        entreprise_phone: "0691234569",
        siret: "23456789023",
        price: "$750",
        city: "Bordeaux"
    }
];

export default projects;